---
- name: Install IIS Web Server Role and Features
  win_feature:
    name:
      - Web-Server
      - Web-Asp-Net45
      - Web-Mgmt-Console
      - Web-Http-Redirect
      - Web-Filtering
      - Web-Request-Monitor
      - Web-Security
    state: present
    include_sub_features: yes
  register: iis_install

- name: Reboot if required after IIS install
  win_reboot:
  when: iis_install.reboot_required
